# Generated by Django 4.2.23 on 2026-04-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="category",
            field=models.CharField(
                choices=[
                    ("salary", "Salary Inquiry"),
                    ("attendance", "Attendance Issue"),
                    ("technical", "Technical Support"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
